---
- hosts: cosmos_chain_server
  become: true
  vars:
    grafana_version: "9.5.2"
    mimir_version: "2.9.0"
    grafana_admin_password: "SecurePassword123!"  # Change this to a secure password
    mimir_retention_period: "15d"
    grafana_alloy_version: "latest"
  tasks:
    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - software-properties-common
          - wget
          - curl
          - gnupg2
          - docker.io
        state: present
        update_cache: yes

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present

    - name: Install Grafana
      apt:
        name: "grafana={{ grafana_version }}"
        state: present

    - name: Configure Grafana
      template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
      notify: Restart Grafana

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Create Docker network
      docker_network:
        name: monitoring-network
        state: present

    - name: Deploy Grafana Alloy
      docker_container:
        name: grafana-alloy
        image: "grafana/grafana-alloy:{{ grafana_alloy_version }}"
        state: started
        ports:
          - "3001:3000"
        networks:
          - name: monitoring-network

    - name: Deploy Mimir
      docker_container:
        name: mimir
        image: "grafana/mimir:{{ mimir_version }}"
        state: started
        ports:
          - "9009:9009"
        networks:
          - name: monitoring-network
        volumes:
          - /etc/mimir:/etc/mimir
        command: "-config.file=/etc/mimir/mimir-config.yaml"

    - name: Configure Grafana datasources
      copy:
        dest: /etc/grafana/provisioning/datasources/datasources.yaml
        content: |
          apiVersion: 1
          datasources:
            - name: Mimir
              type: prometheus
              url: http://mimir:9009/prometheus
              access: proxy
              isDefault: true
            - name: Grafana Alloy
              type: prometheus
              url: http://grafana-alloy:3000/metrics
              access: proxy

  handlers:
    - name: Restart Grafana
      systemd:
        name: grafana-server
        state: restarted
